# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparse_patch_top_intensities <- function(pixels_in_order, number_of_pixels_to_sample, data_rows, data_cols, exclusion_disc_data) {
    .Call(`_TDAExplore_sparse_patch_top_intensities`, pixels_in_order, number_of_pixels_to_sample, data_rows, data_cols, exclusion_disc_data)
}

